### ISSUE TITLE
Error when running ng build

### ISSUE THREAD

**Issue by glysns** [primefaces/sakai-ng#10]
Hello,
First, this template is very nice, always Prime Tech making a good job for the community.

Is it possible helpe me ?

```
15 | // Exports
16 | /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (___CSS_LOADER_EXPORT___);
17 |

```
Thanks

**Comment by alkxyly** [comment]
The resolution is in this link

* https://github.com/primefaces/sakai-ng/pull/8/commits/9a86a497b263f541394336dffab2d66bbdb48f69
