### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by crick77** [primefaces/sakai-ng#18]
Hello!

npm install returns error due to a conflict between package.json primeicons version 6.0.1 and primeng 14.1.1 one which is 5.0.x
Updating package.json to primeng 14.1.2 solves the problem.

Hope to help!
Bye

**Comment by gucal** [comment]
Now the problem does not appear. Does your problem persist?

**Comment by gucal** [comment]
I could not reproduce the problem. Please reactivate the issue if the problem persists.

Thanks for reporting.
