### ISSUE TITLE
Dropdown inside modal

### ISSUE THREAD

**Issue by marc-dev0** [primefaces/sakai-ng#19]
the dropdown inside a modal and placing it in the footer of the modal when collapsing it, the elements cannot be seen correctly, that is, it does not overlap the buttons or the footer of the modal 
There is any solution for this?

**Comment by gucal** [comment]
Hi,
Please can you send a reproduce?

**Comment by cetincakiroglu** [comment]
> 

Hi, 

Dropdown has **appendTo** property to overcome this issue. Please try `appendTo="body"`
