### ISSUE TITLE
Schema validation failed on ng serve

### ISSUE THREAD

**Issue by MarioMunueraPerez** [primefaces/sakai-ng#20]
Schema validation failed with the following errors:
  Data path "['build']" should NOT have additional properties(defaultConfiguration).
Error: Schema validation failed with the following errors:
  Data path "['build']" should NOT have additional properties(defaultConfiguration).

**Comment by gucal** [comment]
Hi,

I could not reproduce the problem. Please reactivate the issue if the problem persists.

Thanks for reporting.
