### ISSUE TITLE
Font files are missing 

### ISSUE THREAD

**Issue by NagornovAlex** [primefaces/sakai-ng#40]
Hi!

There is no font files for lara (blue, indigo) themes:

![image](https://github.com/primefaces/sakai-ng/assets/3100132/7d0ca734-bd1b-4996-9f56-44ec09cf62c9)

@font-face {
  font-family: "Inter var";
  font-weight: 100 900;
  font-display: swap;
  font-style: normal;
  font-named-instance: "Regular";
  src: url("./fonts/Inter-roman.var.woff2?v=3.19") format("woff2");      /* Missing */
}

@font-face {
  font-family: "Inter var";
  font-weight: 100 900;
  font-display: swap;
  font-style: italic;
  font-named-instance: "Italic";
  src: url("./fonts/Inter-italic.var.woff2?v=3.19") format("woff2");     /* Missing */
}

**Comment by mehmetakbudak** [comment]
Hi!
You can download it from the link below. You can create a fonts folder in the _lara-light-indigo_ folder and copy the file you downloaded into it. 

[https://www.cdnpkg.com/inter-ui/file/Inter-roman.var.woff2](url)

**Comment by NagornovAlex** [comment]
Cool thanks!
also link for italic:
https://www.cdnpkg.com/inter-ui/file/Inter-italic.var.woff2/
