### ISSUE TITLE
Index.html File Url Not Found

### ISSUE THREAD

**Issue by sfd-mhrana** [primefaces/sakai-ng#43]
![image](https://github.com/primefaces/sakai-ng/assets/99222296/801dc0a1-d9af-4b69-b63b-1f96fcefb2e5)
this is reffer image. where when i build angular 17 application then assets image, css not found. how i can resolve this??

**Comment by Adrian2422** [comment]
Make sure that the file paths in your application are correct and the files are in the specified directories. Additionally, check whether the `assets` directory is visible in `angular.json`:
```
"assets": [
  "src/favicon.ico",
  "src/assets"
],
```

**Comment by sfd-mhrana** [comment]
Thanks for reply . Solve it with related you solution.
