### ISSUE TITLE
Right to Left support

### ISSUE THREAD

**Issue by bodeg** [primefaces/sakai-ng#6]
Question: is Right to Left supported by Sakai?

**Comment by cetincakiroglu** [comment]
Hi, 

RTL support is not supported by Sakai, whereas we have RTL Templates available like PoseidonNG and you can find them in our library.

**Comment by IncreMan** [comment]
> Question: is Right to Left supported by Sakai?

I have decided to help community with self-made CSS file for RTL.
As a bonus I have added scrollbar design that uses template's variables.
[https://stackoverflow.com/questions/78989814/rtl-scrollbar-css-for-sakai-primevue-free-template/](https://stackoverflow.com/questions/78989814/rtl-scrollbar-css-for-sakai-primevue-free-template/)
